# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/luatzori/ParFullCMS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/luatzori/ParFullCMS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/luatzori/ParFullCMS/CMakeFiles /data/luatzori/ParFullCMS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/luatzori/ParFullCMS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ParFullCMS

# Build rule for target.
ParFullCMS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParFullCMS
.PHONY : ParFullCMS

# fast build rule for target.
ParFullCMS/fast:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/build
.PHONY : ParFullCMS/fast

ParmainApplication.o: ParmainApplication.cc.o
.PHONY : ParmainApplication.o

# target to build an object file
ParmainApplication.cc.o:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/ParmainApplication.cc.o
.PHONY : ParmainApplication.cc.o

ParmainApplication.i: ParmainApplication.cc.i
.PHONY : ParmainApplication.i

# target to preprocess a source file
ParmainApplication.cc.i:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/ParmainApplication.cc.i
.PHONY : ParmainApplication.cc.i

ParmainApplication.s: ParmainApplication.cc.s
.PHONY : ParmainApplication.s

# target to generate assembly for a file
ParmainApplication.cc.s:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/ParmainApplication.cc.s
.PHONY : ParmainApplication.cc.s

src/MyDetectorConstruction.o: src/MyDetectorConstruction.cc.o
.PHONY : src/MyDetectorConstruction.o

# target to build an object file
src/MyDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyDetectorConstruction.cc.o
.PHONY : src/MyDetectorConstruction.cc.o

src/MyDetectorConstruction.i: src/MyDetectorConstruction.cc.i
.PHONY : src/MyDetectorConstruction.i

# target to preprocess a source file
src/MyDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyDetectorConstruction.cc.i
.PHONY : src/MyDetectorConstruction.cc.i

src/MyDetectorConstruction.s: src/MyDetectorConstruction.cc.s
.PHONY : src/MyDetectorConstruction.s

# target to generate assembly for a file
src/MyDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyDetectorConstruction.cc.s
.PHONY : src/MyDetectorConstruction.cc.s

src/MyDetectorMessenger.o: src/MyDetectorMessenger.cc.o
.PHONY : src/MyDetectorMessenger.o

# target to build an object file
src/MyDetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyDetectorMessenger.cc.o
.PHONY : src/MyDetectorMessenger.cc.o

src/MyDetectorMessenger.i: src/MyDetectorMessenger.cc.i
.PHONY : src/MyDetectorMessenger.i

# target to preprocess a source file
src/MyDetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyDetectorMessenger.cc.i
.PHONY : src/MyDetectorMessenger.cc.i

src/MyDetectorMessenger.s: src/MyDetectorMessenger.cc.s
.PHONY : src/MyDetectorMessenger.s

# target to generate assembly for a file
src/MyDetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyDetectorMessenger.cc.s
.PHONY : src/MyDetectorMessenger.cc.s

src/MyEventAction.o: src/MyEventAction.cc.o
.PHONY : src/MyEventAction.o

# target to build an object file
src/MyEventAction.cc.o:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyEventAction.cc.o
.PHONY : src/MyEventAction.cc.o

src/MyEventAction.i: src/MyEventAction.cc.i
.PHONY : src/MyEventAction.i

# target to preprocess a source file
src/MyEventAction.cc.i:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyEventAction.cc.i
.PHONY : src/MyEventAction.cc.i

src/MyEventAction.s: src/MyEventAction.cc.s
.PHONY : src/MyEventAction.s

# target to generate assembly for a file
src/MyEventAction.cc.s:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyEventAction.cc.s
.PHONY : src/MyEventAction.cc.s

src/MyPrimaryGeneratorAction.o: src/MyPrimaryGeneratorAction.cc.o
.PHONY : src/MyPrimaryGeneratorAction.o

# target to build an object file
src/MyPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyPrimaryGeneratorAction.cc.o
.PHONY : src/MyPrimaryGeneratorAction.cc.o

src/MyPrimaryGeneratorAction.i: src/MyPrimaryGeneratorAction.cc.i
.PHONY : src/MyPrimaryGeneratorAction.i

# target to preprocess a source file
src/MyPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyPrimaryGeneratorAction.cc.i
.PHONY : src/MyPrimaryGeneratorAction.cc.i

src/MyPrimaryGeneratorAction.s: src/MyPrimaryGeneratorAction.cc.s
.PHONY : src/MyPrimaryGeneratorAction.s

# target to generate assembly for a file
src/MyPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyPrimaryGeneratorAction.cc.s
.PHONY : src/MyPrimaryGeneratorAction.cc.s

src/MyRunAction.o: src/MyRunAction.cc.o
.PHONY : src/MyRunAction.o

# target to build an object file
src/MyRunAction.cc.o:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyRunAction.cc.o
.PHONY : src/MyRunAction.cc.o

src/MyRunAction.i: src/MyRunAction.cc.i
.PHONY : src/MyRunAction.i

# target to preprocess a source file
src/MyRunAction.cc.i:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyRunAction.cc.i
.PHONY : src/MyRunAction.cc.i

src/MyRunAction.s: src/MyRunAction.cc.s
.PHONY : src/MyRunAction.s

# target to generate assembly for a file
src/MyRunAction.cc.s:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyRunAction.cc.s
.PHONY : src/MyRunAction.cc.s

src/MySteppingAction.o: src/MySteppingAction.cc.o
.PHONY : src/MySteppingAction.o

# target to build an object file
src/MySteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MySteppingAction.cc.o
.PHONY : src/MySteppingAction.cc.o

src/MySteppingAction.i: src/MySteppingAction.cc.i
.PHONY : src/MySteppingAction.i

# target to preprocess a source file
src/MySteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MySteppingAction.cc.i
.PHONY : src/MySteppingAction.cc.i

src/MySteppingAction.s: src/MySteppingAction.cc.s
.PHONY : src/MySteppingAction.s

# target to generate assembly for a file
src/MySteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MySteppingAction.cc.s
.PHONY : src/MySteppingAction.cc.s

src/MyUserActionInitialization.o: src/MyUserActionInitialization.cc.o
.PHONY : src/MyUserActionInitialization.o

# target to build an object file
src/MyUserActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyUserActionInitialization.cc.o
.PHONY : src/MyUserActionInitialization.cc.o

src/MyUserActionInitialization.i: src/MyUserActionInitialization.cc.i
.PHONY : src/MyUserActionInitialization.i

# target to preprocess a source file
src/MyUserActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyUserActionInitialization.cc.i
.PHONY : src/MyUserActionInitialization.cc.i

src/MyUserActionInitialization.s: src/MyUserActionInitialization.cc.s
.PHONY : src/MyUserActionInitialization.s

# target to generate assembly for a file
src/MyUserActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/ParFullCMS.dir/build.make CMakeFiles/ParFullCMS.dir/src/MyUserActionInitialization.cc.s
.PHONY : src/MyUserActionInitialization.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ParFullCMS"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ParmainApplication.o"
	@echo "... ParmainApplication.i"
	@echo "... ParmainApplication.s"
	@echo "... src/MyDetectorConstruction.o"
	@echo "... src/MyDetectorConstruction.i"
	@echo "... src/MyDetectorConstruction.s"
	@echo "... src/MyDetectorMessenger.o"
	@echo "... src/MyDetectorMessenger.i"
	@echo "... src/MyDetectorMessenger.s"
	@echo "... src/MyEventAction.o"
	@echo "... src/MyEventAction.i"
	@echo "... src/MyEventAction.s"
	@echo "... src/MyPrimaryGeneratorAction.o"
	@echo "... src/MyPrimaryGeneratorAction.i"
	@echo "... src/MyPrimaryGeneratorAction.s"
	@echo "... src/MyRunAction.o"
	@echo "... src/MyRunAction.i"
	@echo "... src/MyRunAction.s"
	@echo "... src/MySteppingAction.o"
	@echo "... src/MySteppingAction.i"
	@echo "... src/MySteppingAction.s"
	@echo "... src/MyUserActionInitialization.o"
	@echo "... src/MyUserActionInitialization.i"
	@echo "... src/MyUserActionInitialization.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

